export enum AttributeNames {
  Version = 'version',
  Viewport = 'Viewport',
  Canvas = 'Canvas',
  CanvasFullScreen = 'Canvas Full Screen',
  CanvasWidth = 'Canvas Width',
  CanvasHeight = 'Canvas Height',
  Rotation = 'Rotation',
  ZoomLevel = 'Zoom Level',
  MousePosition = 'Mouse Position',
  PositionX = 'Position X',
  PositionY = 'Position Y',
  Methods = 'Methods',
  PreProcessingMethods = 'PreProcessing Methods',
  PostProcessingMethods = 'PostProcessing Methods',
  MainMethods = 'Main Methods',
  MethodEnum = 'MethodEnum',
  MethodScale = 'MethodScale',
  Shmuck = 'Shmuck',
  DiscreteGradient = 'Discrete Gradient',
  ColorCount = 'Colour Count',
  R = 'R',
  G = 'G',
  B = 'B',
  H = 'H',
  S = 'S',
  V = 'V',
}
